-- Alerts before the date. docs/adr/0010-alerts-before-the-date.md.

-- A team's alert settings, one row per installation of the GitHub App. Keyed by the installation,
-- not the account login: a login can be renamed and taken by someone else, an installation id
-- cannot, and uninstalling removes the settings with everything else.
create table alert_settings (
  installation_id bigint      primary key references installation(id) on delete cascade,
  enabled         boolean     not null default true,
  -- ["a@example.com", ...], at most ten, lower case.
  emails          jsonb       not null default '[]',
  -- Only ever an https://hooks.slack.com/services/... URL; the app refuses anything else.
  slack_webhook   text,
  -- Days before the effective date at which to warn, largest first.
  thresholds      jsonb       not null default '[30, 7]',
  updated_by      text,
  updated_at      timestamptz not null default now()
);

-- What was sent, so nothing is sent twice. One row per finding, effective date, threshold and
-- channel ("slack", or "email:" and the address). The date is part of the key so a moved date is
-- a new warning; a failed send writes no row, so the next run tries again.
create table alert_sent (
  repo_id     bigint      not null references repo(id) on delete cascade,
  contract_id text        not null,
  change_id   text        not null,
  effective   date        not null,
  threshold   integer     not null,
  channel     text        not null,
  sent_at     timestamptz not null default now(),
  primary key (repo_id, contract_id, change_id, effective, threshold, channel)
);

-- Public email alerts from the calendar page. Only the address, its provider filter, whether it
-- was confirmed, and when. An unconfirmed row is removed after a week; unsubscribing deletes it.
create table subscriber (
  email           text        primary key,
  -- Comma-separated provider ids; empty means every provider.
  providers       text        not null default '',
  confirmed_at    timestamptz,
  created_at      timestamptz not null default now(),
  confirm_sent_at timestamptz
);

create table subscriber_sent (
  email     text        not null references subscriber(email) on delete cascade,
  change_id text        not null,
  effective date        not null,
  threshold integer     not null,
  sent_at   timestamptz not null default now(),
  primary key (email, change_id, effective, threshold)
);

-- The key that signs confirmation and unsubscribe links. Generated by the app on first use, so
-- there is nothing to configure; deleting the row invalidates every link already sent.
create table signing_key (
  name       text        primary key,
  secret     bytea       not null,
  created_at timestamptz not null default now()
);
