source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 7.2.1"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "stripe", "~> 13.3"
gem "twilio-ruby", "~> 7.3"
gem "sendgrid-ruby", "~> 6.7"

group :development, :test do
  gem "rspec-rails", "~> 7.0"
end
