package dev.docswatcher.app.auth;

import java.time.Duration;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.bind.DefaultValue;

/**
 * Sign-in with GitHub: the App's OAuth half.
 *
 * <p>Bound from the same {@code docswatcher.github} prefix as the rest of the App's settings, so
 * the client id sits beside the app id it belongs to, and the client secret is read like the
 * private key: from {@code /run/secrets/docswatcher.github.client-secret} through the config tree.
 * A separate record rather than two more fields on {@code AppProperties.GitHub}, so nothing that
 * constructs that record has to change.
 *
 * @param clientId the App's client id, public ({@code GITHUB_CLIENT_ID})
 * @param clientSecret generated by the App's owner; a secret file, not an environment variable
 * @param webBase where the browser signs in and the code is exchanged
 * @param apiBase the REST API the user token is spent on
 * @param sessionTtl how long a signed-in session lasts before signing in again
 */
@ConfigurationProperties(prefix = "docswatcher.github")
public record OAuthProperties(
    String clientId,
    String clientSecret,
    @DefaultValue("https://github.com") String webBase,
    @DefaultValue("https://api.github.com") String apiBase,
    @DefaultValue("8h") Duration sessionTtl) {

  /** Both halves present. Without them the sign-in routes answer 503 and the site says so. */
  public boolean enabled() {
    return clientId != null && !clientId.isBlank() && clientSecret != null && !clientSecret.isBlank();
  }
}
